<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_active_flaticon-edit</name>
   <tag></tag>
   <elementGuidId>a10e37d6-1bb6-4ef4-be45-519c16366786</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.flaticon-edit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flaticon-edit</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography&quot;]/app-root[1]/app-navigation-manager[@class=&quot;ng-star-inserted&quot;]/main[1]/mat-sidenav-container[@class=&quot;mat-drawer-container mat-sidenav-container customScrollbar&quot;]/mat-sidenav-content[@class=&quot;mat-drawer-content mat-sidenav-content&quot;]/div[@class=&quot;example-sidenav-content&quot;]/app-avatar-list[@class=&quot;ng-star-inserted&quot;]/section[@class=&quot;w-100 mt-2 collection_manager&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;whitebgbox&quot;]/div[@class=&quot;kt-container mb-5 pb-5&quot;]/div[@class=&quot;avatar_content&quot;]/div[@class=&quot;mat_table_content customScrollbar&quot;]/table[@class=&quot;mat-table cdk-table mat-elevation-z8 w-100&quot;]/tbody[1]/tr[@class=&quot;mat-row cdk-row ng-star-inserted&quot;]/td[@class=&quot;mat-cell cdk-cell actionColumn cdk-column-Action mat-column-Action ng-star-inserted&quot;]/a[@class=&quot;text-primary mr-3&quot;]/i[@class=&quot;flaticon-edit&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/i</value>
   </webElementXpaths>
</WebElementEntity>
