<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Most Active Users</name>
   <tag></tag>
   <elementGuidId>ad18b1d9-023a-4b03-867b-a0e656ed63c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#widget_dashboard_6-1 > div.grid-stack-item-content.ui-draggable-handle.dashboardner > div.headingDb > i.fa.fa-user</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='widget_dashboard_6-1']/div[2]/div/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-user</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;widget_dashboard_6-1&quot;)/div[@class=&quot;grid-stack-item-content ui-draggable-handle dashboardner&quot;]/div[@class=&quot;headingDb&quot;]/i[@class=&quot;fa fa-user&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='widget_dashboard_6-1']/div[2]/div/i</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[17]/div[2]/div/i</value>
   </webElementXpaths>
</WebElementEntity>
