<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Twitter_checkmark</name>
   <tag></tag>
   <elementGuidId>4c0a19df-4ab4-4d55-af77-53887a97f8ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ulEntifilSource > li > label.checkbox-custom > span.checkmark</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='ulEntifilSource']/li[1]/label/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkmark</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ulEntifilSource&quot;)/li[1]/label[@class=&quot;checkbox-custom&quot;]/span[@class=&quot;checkmark&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ulEntifilSource']/li/label/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/ul/li/label/span</value>
   </webElementXpaths>
</WebElementEntity>
